//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Library_yash.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Register1
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<long> PhoneNo { get; set; }
        public string MailId { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
