//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_yash.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Register
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please Enter LastName")]
        [StringLength(30, MinimumLength = 3)]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Please Enter FirstName")]
        [StringLength(30, MinimumLength = 3)]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Please Enter PhoneNo.")]
        [RegularExpression(@"^(\d{10})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public Nullable<long> PhoneNo { get; set; }
        [Required(ErrorMessage = "Please Enter MailId.")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string MailId { get; set; }
        [Required(ErrorMessage = "Please Enter Gender.")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Enter City.")]
        public string City { get; set; }
        [Required(ErrorMessage = "Please Enter UserName.")]
        [StringLength(30, MinimumLength = 3)]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Please Enter Password.")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}
